Repository mkaburis/Study_Hopper, pull requests merged in 2020-04, with the labels that each got.

#41 Add classes profile
  .idea/dictionaries/runin.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/study_dev/testbed/studyhopper/Dashboard.java
  app/src/main/java/study_dev/testbed/studyhopper/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/Login.java
  app/src/main/java/study_dev/testbed/studyhopper/StudentClass.java
  app/src/main/java/study_dev/testbed/studyhopper/models/Major.java
  app/src/main/java/study_dev/testbed/studyhopper/models/Profile.java
  app/src/main/java/study_dev/testbed/studyhopper/models/StudentClass.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ClassesListAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileClasses.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileMain.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfilePage.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/SectionsPagerAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/classListItem.java
  app/src/main/res/layout/activity_profile_page.xml
  app/src/main/res/layout/class_item.xml
  app/src/main/res/layout/fragment_profile_classes.xml
  app/src/main/res/layout/fragment_profile_main.xml
  app/src/main/res/values/strings.xml
Labels: Firebase, enhancement, medium

#42 Add forget password button
  app/src/main/java/study_dev/testbed/studyhopper/Login.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: easy, task

#43 Firebase courses and groups
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/study_dev/testbed/studyhopper/CreateGroup.java
  app/src/main/java/study_dev/testbed/studyhopper/Dashboard.java
  app/src/main/java/study_dev/testbed/studyhopper/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/Group.java
  app/src/main/java/study_dev/testbed/studyhopper/GroupAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/GroupMemberList.java
  app/src/main/java/study_dev/testbed/studyhopper/Messages.java
  app/src/main/java/study_dev/testbed/studyhopper/MyGroups.java
  app/src/main/java/study_dev/testbed/studyhopper/SessionDetails.java
  app/src/main/java/study_dev/testbed/studyhopper/SessionPage.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyGroupActivity.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyGroupAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyLocationsMap.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileMain.java
  app/src/main/res/drawable/highlight.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_add_group.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_finder_icon.xml
  app/src/main/res/drawable/ic_group_color_blue.xml
  app/src/main/res/drawable/ic_group_color_brown.xml
  app/src/main/res/drawable/ic_group_color_gray.xml
  app/src/main/res/drawable/ic_group_color_green.xml
  app/src/main/res/drawable/ic_group_color_orange.xml
  app/src/main/res/drawable/ic_group_color_purple.xml
  app/src/main/res/drawable/ic_group_color_red.xml
  app/src/main/res/drawable/ic_group_color_yellow.xml
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/layout/activity_my_groups.xml
  app/src/main/res/layout/activity_session_details.xml
  app/src/main/res/layout/activity_session_page.xml
  app/src/main/res/layout/activity_study_group.xml
  app/src/main/res/layout/dialogue_group_max_size.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/group_card.xml
  app/src/main/res/menu/my_groups_menu.xml
  app/src/main/res/menu/study_group_menu.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Firebase, GUI, help wanted, task

#45 Moved java files into subdirectories by group
  app/src/main/AndroidManifest.xml
  app/src/main/java/study_dev/testbed/studyhopper/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/Login.java
  app/src/main/java/study_dev/testbed/studyhopper/MainActivity.java
  app/src/main/java/study_dev/testbed/studyhopper/Major.java
  app/src/main/java/study_dev/testbed/studyhopper/Profile.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyRoomReservations.java
  app/src/main/java/study_dev/testbed/studyhopper/models/Group.java
  app/src/main/java/study_dev/testbed/studyhopper/models/studyGroupItem.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/CreateGroup.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/Dashboard.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/DashboardViewModel.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/GroupAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/MyGroups.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/StudyGroupAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/StudyGroupFinder.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/messages/Messages.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileMain.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/sessions/SessionPage.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/GroupMemberList.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/StudyGroupActivity.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyLocation/StudyLocationsFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyLocation/StudyLocationsMap.java
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_group_members_list.xml
  app/src/main/res/layout/activity_messages.xml
  app/src/main/res/layout/activity_my_groups.xml
  app/src/main/res/layout/activity_session_page.xml
  app/src/main/res/layout/activity_study_group.xml
  app/src/main/res/layout/activity_study_group_finder.xml
  app/src/main/res/layout/activity_study_locations_map.xml
Labels: easy

#48 Dashboard group adapter update
  app/src/main/java/study_dev/testbed/studyhopper/models/studyGroupItem.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/CreateGroup.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/Dashboard.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/GroupAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/MyGroups.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/StudyGroupAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/messages/Messages.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/sessions/SessionPage.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/GroupMemberList.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/StudyGroupActivity.java
  app/src/main/res/layout/group_card.xml
Labels: easy, help wanted, task

#54 Refactor code to use auto-generated id for user profiles
  app/src/main/java/study_dev/testbed/studyhopper/models/Profile.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/CreateGroup.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/Dashboard.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/MyGroups.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileClasses.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileMain.java
Labels: Firebase, medium, task

#58 Add searchable fields group
  app/src/main/java/study_dev/testbed/studyhopper/models/Group.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/CreateGroup.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/StudyGroupFinderFragment.java
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/values/strings.xml
Labels: Firebase, GUI, easy, enhancement

#61 Study sessions
  app/src/main/AndroidManifest.xml
  app/src/main/java/study_dev/testbed/studyhopper/models/Group.java
  app/src/main/java/study_dev/testbed/studyhopper/models/Session.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/CreateGroup.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/MyGroups.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/PeopleSearchFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/sessions/CreateSession.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/sessions/Session.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/sessions/SessionAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/sessions/SessionPage.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/GroupMemberList.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/StudyGroupActivity.java
  app/src/main/res/drawable/ic_collaborative_session.xml
  app/src/main/res/drawable/ic_quiet_session.xml
  app/src/main/res/drawable/ic_review_session.xml
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/layout/activity_create_session.xml
  app/src/main/res/layout/activity_session.xml
  app/src/main/res/layout/activity_session_page.xml
  app/src/main/res/layout/activity_study_group.xml
  app/src/main/res/layout/session_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, help wanted, medium, task

#62 Added Searchable user page
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/study_dev/testbed/studyhopper/MainActivity.java
  app/src/main/java/study_dev/testbed/studyhopper/models/Profile.java
  app/src/main/java/study_dev/testbed/studyhopper/models/StudentClass.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/PeopleSearchAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/PeopleSearchFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/StudyGroupFinderFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/peopleListItem.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ClassesListAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileViewer.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/GroupMemberList.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/MemberAdapter.java
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/layout/activity_profile_viewer.xml
  app/src/main/res/layout/fragment_people_search.xml
  app/src/main/res/layout/fragment_study_group_finder.xml
  app/src/main/res/values/strings.xml
Labels: Firebase, GUI, easy, enhancement

#64 Searchable group viewer
  app/src/main/AndroidManifest.xml
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/GroupSearchAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/StudyGroupFinderFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/groupListItem.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/peopleListItem.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileClasses.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ProfileViewer.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/GroupMemberList.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/GroupViewer.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/MemberAdapter.java
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/layout/activity_group_viewer.xml
  app/src/main/res/layout/fragment_profile_main.xml
  app/src/main/res/values/strings.xml
Labels: Firebase, GUI, enhancement, medium

#63 Modify groups
  app/src/main/java/study_dev/testbed/studyhopper/models/Group.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/CreateGroup.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/groupFinder/StudyGroupFinderFragment.java
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/layout/fragment_study_group_finder.xml
Labels: easy

#65 Study Session Activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/study_dev/testbed/studyhopper/models/Session.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/sessions/Session.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/sessions/SessionActivity.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/StudyGroupActivity.java
  app/src/main/res/drawable/ic_alert_icon.xml
  app/src/main/res/drawable/ic_happy_face.xml
  app/src/main/res/drawable/ic_mic.xml
  app/src/main/res/drawable/ic_neutral_face.xml
  app/src/main/res/drawable/ic_sad_face.xml
  app/src/main/res/drawable/ic_session_location.xml
  app/src/main/res/layout/activity_session.xml
  app/src/main/res/values/strings.xml
Labels: Firebase, GUI, enhancement, task

#66 final prodution touches
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/Dashboard.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/MyGroups.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/profile/ClassesListAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/GroupMemberList.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/GroupViewer.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/studyGroup/StudyGroupActivity.java
  app/src/main/res/values/strings.xml
Labels: easy
