Repository mkaburis/Study_Hopper, pull requests merged in 2020-03, with the labels that each got.

#25 Profile page gui
  .idea/dictionaries/runin.xml
  .idea/misc.xml
  .idea/render.experimental.xml
  app/build.gradle
  app/src/main/java/study_dev/testbed/studyhopper/Dashboard.java
  app/src/main/java/study_dev/testbed/studyhopper/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/Login.java
  app/src/main/java/study_dev/testbed/studyhopper/MainActivity.java
  app/src/main/java/study_dev/testbed/studyhopper/ProfilePage.java
  app/src/main/java/study_dev/testbed/studyhopper/SessionDetails.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyGroupDetails.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyGroupFinder.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/dashboard/DashboardViewModel.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/main/PageViewModel.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/main/PlaceholderFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/notifications/NotificationsFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/ui/notifications/NotificationsViewModel.java
  app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  app/src/main/res/drawable/ic_home_black_24dp.xml
  app/src/main/res/drawable/ic_notifications_black_24dp.xml
  app/src/main/res/drawable/usflib.jpg
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile_page.xml
  app/src/main/res/layout/activity_study_locations_map.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_study_group_details.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/menu/menu_study_group_finder.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: medium, task

#30 Auto populate Profile
  app/src/main/java/study_dev/testbed/studyhopper/ProfilePage.java
  app/src/main/res/layout/activity_profile_page.xml
Labels: easy, enhancement, task

#31 Login system improvements
  app/src/main/java/study_dev/testbed/studyhopper/DashboardFragment.java
  app/src/main/res/drawable/study_hopper_mast.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/values/strings.xml
Labels: easy, enhancement, task

#36 Change Profile to use Classes instead of Hashmaps
  .idea/dictionaries/runin.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/render.experimental.xml
  .idea/vcs.xml
  app/src/main/java/study_dev/testbed/studyhopper/Dashboard.java
  app/src/main/java/study_dev/testbed/studyhopper/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/Major.java
  app/src/main/java/study_dev/testbed/studyhopper/Profile.java
  app/src/main/java/study_dev/testbed/studyhopper/ProfilePage.java
  app/src/main/java/study_dev/testbed/studyhopper/StudentClass.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_profile_page.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/mipmap-anydpi-v26/ic_profile_image.xml
  app/src/main/res/mipmap-anydpi-v26/ic_profile_image_round.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: easy, task

#39 Study group gui
  .gitignore
  .idea/dictionaries/runin.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/study_dev/testbed/studyhopper/DashboardFragment.java
  app/src/main/java/study_dev/testbed/studyhopper/GroupMemberList.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyGroupActivity.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyGroupAdapter.java
  app/src/main/java/study_dev/testbed/studyhopper/StudyGroupDetails.java
  app/src/main/java/study_dev/testbed/studyhopper/studyGroupItem.java
  app/src/main/res/drawable/ic_chat_icon.xml
  app/src/main/res/drawable/ic_group_member.xml
  app/src/main/res/drawable/ic_study_group_stats.xml
  app/src/main/res/drawable/ic_study_sessions.xml
  app/src/main/res/layout/activity_group_members_list.xml
  app/src/main/res/layout/activity_study_group.xml
  app/src/main/res/layout/activity_study_group_details.xml
  app/src/main/res/mipmap-hdpi/ic_profile_image_round.png
  app/src/main/res/mipmap-mdpi/ic_profile_image.png
  app/src/main/res/mipmap-mdpi/ic_profile_image_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: GUI, help wanted, task
